-- ECHO RESCUE DATABASE SETUP
CREATE DATABASE IF NOT EXISTS ECHO_RESCUE;
USE DATABASE ECHO_RESCUE;
CREATE SCHEMA IF NOT EXISTS PUBLIC;

-- Create the table for processed flood data
CREATE OR REPLACE TABLE V_BLOCKED_ROADS (
    ROAD_NAME STRING,
    SEVERITY STRING,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    REPORTED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Insert dummy data for the demo
INSERT INTO V_BLOCKED_ROADS (ROAD_NAME, SEVERITY, LATITUDE, LONGITUDE) VALUES 
('M-1 Motorway', 'CRITICAL', 34.0151, 71.5249),
('N-55 Indus Highway', 'BLOCKED', 33.6844, 73.0479),
('Kabul River Bridge', 'WARNING', 34.1980, 72.0300);